# Exported from Render on 2025-03-23T12:22:12Z
services:
- type: web
  name: qr_mukilan
  runtime: docker
  repo: https://github.com/Venirails/qr_mukilan
  plan: free
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: job_connect
      property: connectionString
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  region: singapore
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"


